name: Schedule

on:
  schedule:
    - cron: '* * * * *' # تحديد الجدولة الزمنية هنا (في هذا المثال، سيتم تشغيل الرابط كل دقيقة)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: php main/up.php
